/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import {
  OrthographicCamera,
  PerspectiveCamera,
  useGLTF,
} from "@react-three/drei";
import { useLoader } from "@react-three/fiber";
import React, { useRef } from "react";
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader";
// import "../../../public/mim";

export default function My3dRoom(props) {
  const gltf = useLoader(GLTFLoader, "/mini_room_art_copy.gltf");

  return (
    <group>
      <primitive object={gltf.scene} />
      <PerspectiveCamera
        makeDefault
        name="camera"
        fov={2}
        near={0.9}
        far={3000}
        position={[-600, 400, 650]}
      />
    </group>
  );
}

useGLTF.preload("/mini_room_art_copy.gltf");
